"""Initial migration

Revision ID: 584434ba4363
Revises: 87b374290bbb
Create Date: 2023-01-25 21:34:16.078358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584434ba4363'
down_revision = '87b374290bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
