"""initial migration

Revision ID: 87b374290bbb
Revises: 
Create Date: 2023-01-25 20:46:53.049747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b374290bbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paintings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('painting_title', sa.String(length=50), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('current_location', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('painting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('paintings')
    # ### end Alembic commands ###
